### ISSUE TITLE
Please consider adding a link to ls-lint.org in the project header

### ISSUE THREAD

**Issue by ccoVeille** [ls-lint/action#4]
Here is what you have now
![image](https://github.com/ls-lint/action/assets/3875889/2307673a-b235-411a-8eae-6f1c0e21da45)

I would recommend you doing the same as you did with other ls-lint repositories

https://github.com/loeffel-io/ls-lint
![image](https://github.com/ls-lint/action/assets/3875889/b9c303ec-fe2b-4b50-96cb-c8a48958fd27)

https://github.com/ls-lint/docs
![image](https://github.com/ls-lint/action/assets/3875889/50a8dc93-94ae-4460-9246-6c8ac60ae111)

**Comment by loeffel-io** [comment]
good one!
